name: shisoku-test

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: setup C-charp
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 7.0.x
        - name: build
          run: dotnet build
    unit-test:
        runs-on: ubuntu-latest
        permissions:
          pull-requests: write
        steps:
        - uses: actions/checkout@v3
        - name: setup C-charp
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 7.0.x
        - name: build
          run: dotnet build
        - name: Unit Test
          run: dotnet test --no-build --collect:"XPlat Code Coverage" --results-directory ./coverage
        - name: Code Coverage Report
          uses: irongut/CodeCoverageSummary@v1.3.0
          with:
            filename: coverage/**/coverage.cobertura.xml
            badge: true
            fail_below_min: true
            format: markdown
            hide_branch_rate: false
            indicators: true
            output: both
            thresholds: '60 80'
        - name: Add Coverage PR Comment
          uses: marocchino/sticky-pull-request-comment@v2
          if: github.event_name == 'pull_request'
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            recreate: true
            path: code-coverage-results.md
        - name: output html
          run: |
            dotnet tool install -g dotnet-reportgenerator-globaltool
            reportgenerator -reports:"./coverage/*/coverage.cobertura.xml" -targetdir:"report" -reporttypes:"Html"
        - name: Upload coverage report
          uses: actions/upload-artifact@v2
          with:
            name: coverage-report
            path: report/
    integration-test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: setup C-charp
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 7.0.x
        - name: build
          run: dotnet build
        - name: Integration Test
          run: shisoku.Integration/integration_calc.sh
